// frontend-react/src/components/Navbar.jsx
import { useContext } from "react";
import { Link } from "react-router-dom";
import AuthContext from "../context/AuthContext";

const Navbar = () => {
  let { user, logoutUser } = useContext(AuthContext);

  return (
    <nav className="bg-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <Link to="/">
                <img className="h-8 w-8" src="vite.svg" alt="Logo" />
              </Link>
            </div>
            <div>
              <div className="ml-2 sm:ml-4 md:ml-6 flex items-baseline space-x-4">
                <Link
                  to="/"
                  className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                >
                  Home
                </Link>
              </div>
            </div>
          </div>
          <div className="flex items-center">
            <div className="ml-4">
              {user ? (
                <>
                <span                 
                  className="text-blue-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium cursor-pointer"
                >
                  {user.name}
                </span>
                <span
                  onClick={logoutUser}
                  className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium cursor-pointer"
                >
                  Logout
                </span>
                
                
                </>
              ) : (
                <Link
                  to="/login"
                  className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                >
                  Login
                </Link>
              )}
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// frontend-vue/src/components/Navbar.vue
<template>
  <nav class="bg-blue-600 p-4 text-white shadow-md sticky top-0 z-50">
    <div class="w-full mx-auto flex justify-between items-center md:px-8">
      <!-- Left Side -->
      <div class="flex items-center space-x-8">
        <router-link to="/"
          class="text-xl font-medium hover:text-yellow-300 transition-colors duration-200 inline-block"
          active-class="text-yellow-300">
          MyApp
        </router-link>

        
      </div>

      <!-- Right Side -->
      <div class="flex items-center space-x-4">
        <template v-if="!authStore.authTokens">
          <router-link to="/login"
            class="px-4 py-2 rounded hover:bg-blue-500 transition-colors duration-200 font-medium"
            active-class="bg-blue-700">
            Login
          </router-link>          
        </template>
        <template v-else>
          <span class=" mr-2 truncate">{{ authStore.user?.email }}</span>
          <button @click="logout"
            class="px-4 py-2 rounded bg-red-500 hover:bg-red-600 transition-colors duration-200 font-medium">
            Logout
          </button>
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { useAuthStore } from '../stores/auth';
import { useRouter } from 'vue-router';

const authStore = useAuthStore();
const router = useRouter();

const logout = async () => {
  try {
    await authStore.logoutUser();
    router.push('/login');
  } catch (error) {
    console.error('Logout error:', error);
  }
};
</script>

<style scoped>
/* Tambahan agar transisi tetap halus tanpa mengubah ukuran */
.router-link-active {
  transition: color 0.2s ease;
}
</style>
